version: '3.8'

services:
  db:
    build: ./postgres/
    ports:
      - 5432:5432
    networks:
      - app-tier

  python :
    build: ./python/
    volumes:
      - ./python:/app/
    depends_on:
      - db
    networks:
      - app-tier
    command: tail -f /dev/null

networks:
  app-tier:
    driver: bridge